[package]
name = "wasm-pest"
version = "0.1.0"
edition = "2021"
authors = ["sunlee <hildxd@outlook.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pest = "2.5"
pest_fmt = "0.2"
pest_meta = "2.5"
pest_vm = "2.5"
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2"
